services:
  - name: server
    plan: free
    type: web
    env: node
    repo: https://github.com/m3ia/priority-health
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node ./node_modules/db-migrate/bin/db-migrate up && node server.mjs
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: free
    ipAllowList: []